### ISSUE TITLE
Allow tests to be run via cmd with maven

### ISSUE THREAD

**Issue by RubberHux** [tayloh/DD2480-Assignment1#52]
As of right now, tests cannot be run via command line using maven. This is important to fix so that the project can be compiled and run easily via command line.

**Comment by tayloh** [comment]
If it doesn't work / takes too much time: it doesn't explicitly say anywhere in the grading specification or the "Assignment 1 (please read)" discussion post on Canvas that it has to be run/compiled/tested via command line

From "Assignment 1 (please read)":
A good README needs at least:
* A title,
* a short summary,
* information on how to compile, test, and run the code (this can be just the build/test/run command itself),
a statement of contributions.

So, we could (if it comes to it) write like: download Intellij IDEA 2022.3 (? I think), git clone, open as project, run tests from test folder... etc

**Comment by tayloh** [comment]
Got it working (for windows):
1. Download Maven from here https://maven.apache.org/download.cgi
2. Add its bin folder to PATH
3. Locate your Java JDK, add its bin folder to path (mvn needs jdk to be in PATH)
4. cd into our projects folder
5. for tests: mvn test
6. for main method: mvn compile exec:java -Dexec.mainClass="org.labs.lab1.Main

Setting mainClass can be done in the configuration file pom.xml which simplifies the command for running normally:
https://www.baeldung.com/maven-java-main-method

**Comment by tayloh** [comment]
Had to add this:


    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
            </plugin>
        </plugins>
    </build>

to pom.xml for it to find all tests as well (https://cylab.be/blog/15/maven-not-running-all-junit-tests)
